CI: Fix ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -36,11 +36,13 @@ jobs:
       - name: Publish NPM Package
         if: github.ref == 'refs/heads/v5'
         run: |
-          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
+          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ./.npmrc
+          PACKAGE_NAME=$(node -p "require('./package.json').name")
           PACKAGE_VERSION=$(node -p "require('./package.json').version")
-          if npm view your-package-name@$PACKAGE_VERSION > /dev/null 2>&1; then
-            echo "Version $PACKAGE_VERSION already exists."
+          if npm view $PACKAGE_NAME@$PACKAGE_VERSION > /dev/null 2>&1; then
+            echo "$PACKAGE_NAME version $PACKAGE_VERSION already exists."
             exit 0
           fi
+          npm whoami || (echo "❌ NPM_TOKEN invalid!" && exit 1)
           npm publish --access public
         working-directory: ./src
